version: "3.7"

services:
  ui:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./app:/app/app
    command: npm run dev
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14.2-alpine
    env_file:
      - .env