version: "3.7"

services:
  ui:
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    ports:
      - 3000:3000
    volumes:
      - ./app:/src/app
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db